sbatch --export=ALL,input=incompleteOverlap_1.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_10.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_100.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_11.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_12.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_13.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_14.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_15.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_16.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_17.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_18.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_19.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_2.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_20.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_21.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_22.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_23.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_24.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_25.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_26.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_27.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_28.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_29.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_3.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_30.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_31.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_32.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_33.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_34.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_35.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_36.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_37.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_38.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_39.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_4.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_40.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_41.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_42.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_43.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_44.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_45.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_46.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_47.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_48.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_49.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_5.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_50.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_51.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_52.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_53.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_54.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_55.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_56.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_57.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_58.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_59.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_6.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_60.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_61.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_62.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_63.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_64.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_65.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_66.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_67.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_68.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_69.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_7.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_70.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_71.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_72.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_73.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_74.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_75.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_76.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_77.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_78.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_79.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_8.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_80.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_81.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_82.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_83.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_84.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_85.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_86.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_87.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_88.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_89.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_9.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_90.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_91.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_92.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_93.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_94.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_95.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_96.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_97.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_98.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=incompleteOverlap_99.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_1.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_10.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_11.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_12.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_13.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_14.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_15.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_16.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_17.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_18.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_19.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_2.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_20.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_21.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_22.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_23.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_24.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_25.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_3.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_4.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_5.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_6.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_7.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_8.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=noOverlap_9.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_1.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_10.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_11.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_12.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_13.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_14.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_15.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_16.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_17.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_18.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_19.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_2.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_20.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_21.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_22.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_23.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_24.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_25.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_3.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_4.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_5.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_6.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_7.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_8.RDS batchCorrectEval_execute.sh
sbatch --export=ALL,input=totalOverlap_9.RDS batchCorrectEval_execute.sh
